name: eyes_on_the_road
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.5.4
dependencies:
    flutter:
        sdk: flutter
    google_fonts: ^6.2.1
    speech_to_text: ^7.0.0
    flutter_tts: ^3.8.5
    permission_handler: ^11.4.0
    provider: ^6.0.5
    flutter_dotenv: ^5.1.0
    connectivity_plus: ^6.1.3
    geolocator: ^13.0.2
    shared_preferences: ^2.5.2
    sensors_plus: ^6.1.1
    flutter_launcher_icons: ^0.13.1
    socket_io_client: ^2.0.0
    camera: ^0.10.6
    path_provider: ^2.1.5
    path: ^1.9.1
    image: ^4.5.3
    cupertino_icons: ^1.0.8
    flutter_vision: ^1.1.4
    get: ^4.7.2
    google_mlkit_object_detection: ^0.15.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    assets:
        - .env
        - assets/images/street.jpg
        - assets/images/icon.png
        - assets/models/
flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/icon.png"
    remove_alpha_ios: true # Recommended for iOS icons
